"""admin_first_pwd

Revision ID: 096230c10a9d
Revises: 572404f33ff8
Create Date: 2020-06-14 01:53:21.175580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096230c10a9d'
down_revision = '572404f33ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SharingType',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('STid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('STtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('STid')
    )
    op.add_column('Admin', sa.Column('ADfirstname', sa.Text(), nullable=True))
    op.add_column('Admin', sa.Column('ADfirstpwd', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Admin', 'ADfirstpwd')
    op.drop_column('Admin', 'ADfirstname')
    op.drop_table('SharingType')
    # ### end Alembic commands ###
