"""init_user_db

Revision ID: 11ef41aefdca
Revises: 
Create Date: 2020-06-10 17:40:40.504587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11ef41aefdca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddressArea',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AAid', sa.String(length=8), nullable=False),
    sa.Column('AAname', sa.String(length=32), nullable=False),
    sa.Column('ACid', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('AAid')
    )
    op.create_table('AddressCity',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ACid', sa.String(length=8), nullable=False),
    sa.Column('ACname', sa.String(length=20), nullable=False),
    sa.Column('APid', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('ACid')
    )
    op.create_table('AddressProvince',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('APid', sa.String(length=8), nullable=False),
    sa.Column('APname', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('APid')
    )
    op.create_table('Admin',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('ADnum', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('ADname', sa.String(length=255), nullable=True),
    sa.Column('ADtelephone', sa.String(length=13), nullable=True),
    sa.Column('ADpassword', sa.Text(), nullable=False),
    sa.Column('ADheader', sa.Text(), nullable=True),
    sa.Column('ADlevel', sa.Integer(), nullable=True),
    sa.Column('ADstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ADid')
    )
    op.create_table('AdminAction',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AAid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('AAaction', sa.Integer(), nullable=True),
    sa.Column('AAmodel', sa.String(length=255), nullable=True),
    sa.Column('AAdetail', mysql.LONGTEXT(), nullable=True),
    sa.Column('AAkey', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('AAid')
    )
    op.create_table('CashFlow',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CFWid', sa.String(length=64), nullable=False),
    sa.Column('CNid', sa.String(length=64), nullable=False),
    sa.Column('partner_trade_no', sa.String(length=64), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('amout', sa.Integer(), nullable=True),
    sa.Column('cmms_amt', sa.Integer(), nullable=True),
    sa.Column('CFWfrom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CFWid')
    )
    op.create_table('CashNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CNid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('CommisionFor', sa.Integer(), nullable=True),
    sa.Column('CNbankName', sa.Text(), nullable=True),
    sa.Column('CNbankDetail', sa.Text(), nullable=True),
    sa.Column('CNcardNo', sa.String(length=32), nullable=True),
    sa.Column('CNcashNum', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('CNcardName', sa.String(length=32), nullable=True),
    sa.Column('CNstatus', sa.Integer(), nullable=True),
    sa.Column('CNrejectReason', sa.Text(), nullable=True),
    sa.Column('ApplyPlatform', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CNid')
    )
    op.create_table('CoveredCertifiedNameLog',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('CNLid', sa.String(length=64), nullable=False),
    sa.Column('OldName', sa.String(length=255), nullable=True),
    sa.Column('NewName', sa.String(length=255), nullable=True),
    sa.Column('OldIdentityNumber', sa.String(length=64), nullable=True),
    sa.Column('NewIdentityNumber', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('CNLid')
    )
    op.create_table('IDcheck',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('IDCid', sa.String(length=64), nullable=False),
    sa.Column('IDCcode', sa.String(length=24), nullable=False),
    sa.Column('IDCname', sa.Text(), nullable=True),
    sa.Column('IDCresult', sa.Boolean(), nullable=True),
    sa.Column('IDCrealName', sa.Text(), nullable=True),
    sa.Column('IDCcardNo', sa.Text(), nullable=True),
    sa.Column('IDCaddrCode', sa.Text(), nullable=True),
    sa.Column('IDCbirth', sa.Text(), nullable=True),
    sa.Column('IDCsex', sa.Integer(), nullable=True),
    sa.Column('IDCcheckBit', sa.String(length=2), nullable=True),
    sa.Column('IDCaddr', sa.Text(), nullable=True),
    sa.Column('IDCerrorCode', sa.String(length=8), nullable=True),
    sa.Column('IDCreason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('IDCid')
    )
    op.create_table('SharingParameters',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SPSid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('SPScontent', sa.Text(), nullable=True),
    sa.Column('SPSname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('SPSid')
    )
    op.create_table('User',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=255), nullable=False),
    sa.Column('UScustomizeName', sa.String(length=255), nullable=True),
    sa.Column('USrealname', sa.String(length=255), nullable=True),
    sa.Column('UStelephone', sa.String(length=13), nullable=True),
    sa.Column('USgender', sa.Integer(), nullable=True),
    sa.Column('USbirthday', sa.DateTime(), nullable=True),
    sa.Column('UScustomizeBirthday', sa.DateTime(), nullable=True),
    sa.Column('USareaId', sa.String(length=64), nullable=True),
    sa.Column('UScustomizeHeader', sa.Text(), nullable=True),
    sa.Column('USidentification', sa.String(length=24), nullable=True),
    sa.Column('USheader', sa.Text(), nullable=True),
    sa.Column('USopenid1', sa.Text(), nullable=True),
    sa.Column('USopenid2', sa.Text(), nullable=True),
    sa.Column('USopenid3', sa.Text(), nullable=True),
    sa.Column('USunionid', sa.Text(), nullable=True),
    sa.Column('USsupper1', sa.String(length=64), nullable=True),
    sa.Column('USsupper2', sa.String(length=64), nullable=True),
    sa.Column('USsupper3', sa.String(length=64), nullable=True),
    sa.Column('USCommission1', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('USCommission2', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('USCommission3', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('USintegral', sa.Integer(), nullable=True),
    sa.Column('USlevel', sa.Integer(), nullable=True),
    sa.Column('USwxacode', sa.Text(), nullable=True),
    sa.Column('USplayName', sa.String(length=255), nullable=True),
    sa.Column('USminiLevel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('USid')
    )
    op.create_table('UserAccessApi',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UAAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('ULA', sa.String(length=64), nullable=True),
    sa.Column('USTip', sa.String(length=64), nullable=True),
    sa.Column('OSVersion', sa.String(length=25), nullable=True),
    sa.Column('PhoneModel', sa.String(length=16), nullable=True),
    sa.Column('WechatVersion', sa.String(length=16), nullable=True),
    sa.Column('NetType', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('UAAid')
    )
    op.create_table('UserIntegral',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UIid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UIintegral', sa.Integer(), nullable=True),
    sa.Column('UIaction', sa.Integer(), nullable=True),
    sa.Column('UItype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UIid')
    )
    op.create_table('UserInvitation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UINid', sa.String(length=64), nullable=False),
    sa.Column('USInviter', sa.String(length=64), nullable=True),
    sa.Column('USInvited', sa.String(length=64), nullable=True),
    sa.Column('UINapi', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('UINid')
    )
    op.create_table('UserLoginTime',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ULTid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USTip', sa.String(length=64), nullable=True),
    sa.Column('ULtype', sa.Integer(), nullable=True),
    sa.Column('OSVersion', sa.String(length=25), nullable=True),
    sa.Column('PhoneModel', sa.String(length=16), nullable=True),
    sa.Column('WechatVersion', sa.String(length=16), nullable=True),
    sa.Column('NetType', sa.String(length=10), nullable=True),
    sa.Column('UserAgent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ULTid')
    )
    op.create_table('UserMedia',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UMid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UMurl', sa.Text(), nullable=True),
    sa.Column('UMtype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UMid')
    )
    op.create_table('UserWallet',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UWid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('CommisionFor', sa.Integer(), nullable=True),
    sa.Column('UWbalance', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('UWtotal', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('UWcash', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('UWexpect', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('UWid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserWallet')
    op.drop_table('UserMedia')
    op.drop_table('UserLoginTime')
    op.drop_table('UserInvitation')
    op.drop_table('UserIntegral')
    op.drop_table('UserAccessApi')
    op.drop_table('User')
    op.drop_table('SharingParameters')
    op.drop_table('IDcheck')
    op.drop_table('CoveredCertifiedNameLog')
    op.drop_table('CashNotes')
    op.drop_table('CashFlow')
    op.drop_table('AdminAction')
    op.drop_table('Admin')
    op.drop_table('AddressProvince')
    op.drop_table('AddressCity')
    op.drop_table('AddressArea')
    # ### end Alembic commands ###
