"""add_approval

Revision ID: 24f5346afd15
Revises: bc3585a4303c
Create Date: 2020-06-16 19:59:04.871103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24f5346afd15'
down_revision = 'bc3585a4303c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminPermission',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ADPid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('PIid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ADPid')
    )
    op.create_table('Approval',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AVid', sa.String(length=64), nullable=False),
    sa.Column('AVname', sa.String(length=255), nullable=False),
    sa.Column('AVstartid', sa.String(length=64), nullable=False),
    sa.Column('AVlevel', sa.Integer(), nullable=True),
    sa.Column('AVstatus', sa.Integer(), nullable=True),
    sa.Column('AVcontent', sa.String(length=64), nullable=True),
    sa.Column('PTid', sa.String(length=64), nullable=True),
    sa.Column('AVcontentdetail', mysql.LONGTEXT(), nullable=True),
    sa.Column('AVstartdetail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('AVid')
    )
    op.create_table('ApprovalNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ANid', sa.String(length=64), nullable=False),
    sa.Column('AVid', sa.String(length=64), nullable=True),
    sa.Column('AVadname', sa.Text(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('ANaction', sa.Integer(), nullable=True),
    sa.Column('ANabo', sa.Text(), nullable=True),
    sa.Column('ANfrom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ANid')
    )
    op.create_table('Permission',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PEid', sa.String(length=64), nullable=False),
    sa.Column('PELevel', sa.Integer(), nullable=False),
    sa.Column('PIid', sa.String(length=64), nullable=True),
    sa.Column('PTid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('PEid')
    )
    op.create_table('PermissionItems',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PIid', sa.String(length=64), nullable=False),
    sa.Column('PIname', sa.Text(), nullable=True),
    sa.Column('PIstatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PIid')
    )
    op.create_table('PermissionNotes',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PNid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('PNcontent', sa.String(length=64), nullable=True),
    sa.Column('PINaction', sa.Text(), nullable=True),
    sa.Column('PNType', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PNid')
    )
    op.create_table('PermissionType',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PTid', sa.String(length=64), nullable=False),
    sa.Column('PTname', sa.Text(), nullable=True),
    sa.Column('PTmodelName', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('PTid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PermissionType')
    op.drop_table('PermissionNotes')
    op.drop_table('PermissionItems')
    op.drop_table('Permission')
    op.drop_table('ApprovalNotes')
    op.drop_table('Approval')
    op.drop_table('AdminPermission')
    # ### end Alembic commands ###
