"""add_user_location

Revision ID: 31ee01847844
Revises: 3409e9c35023
Create Date: 2020-06-15 16:16:30.296279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ee01847844'
down_revision = '3409e9c35023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserLocation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ULid', sa.String(length=64), nullable=False),
    sa.Column('ULformattedAddress', sa.Text(), nullable=True),
    sa.Column('ULcountry', sa.Text(), nullable=True),
    sa.Column('ULprovince', sa.Text(), nullable=True),
    sa.Column('ULcity', sa.Text(), nullable=True),
    sa.Column('ULdistrict', sa.Text(), nullable=True),
    sa.Column('ULresult', sa.Text(), nullable=True),
    sa.Column('ULlng', sa.Text(), nullable=True),
    sa.Column('ULlat', sa.Text(), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ULid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserLocation')
    # ### end Alembic commands ###
