"""'add_config'

Revision ID: 3a8304b03808
Revises: b32210ec9301
Create Date: 2020-07-05 01:47:06.063447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a8304b03808'
down_revision = 'b32210ec9301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('Commision', sa.Column('CheckTime', sa.Integer(), nullable=True, comment='考核周期，单位：天'))
    op.add_column('Commision', sa.Column('LevelDownOne', sa.Integer(), nullable=True, comment='二级降一级考核人数'))
    op.add_column('Commision', sa.Column('LevelDownOneRep', sa.Integer(), nullable=True, comment='二级降一级考核人数可替代'))
    op.add_column('Commision', sa.Column('LevelDownTwo', sa.Integer(), nullable=True, comment='三级降二级考核人数'))
    op.add_column('Commision', sa.Column('LevelDownTwoRep', sa.Integer(), nullable=True, comment='三级降二级考核人数可替代'))
    op.add_column('Commision', sa.Column('LevelDownZero', sa.Integer(), nullable=True, comment='三级降二级考核人数'))
    op.add_column('Commision', sa.Column('LevelDownZeroRep', sa.Integer(), nullable=True, comment='三级降二级考核人数可替代'))
    op.add_column('Commision', sa.Column('LevelUpThree', sa.Integer(), nullable=True, comment='二级升三级要求人数'))
    op.add_column('Commision', sa.Column('LevelUpThreeReward', sa.DECIMAL(scale=2), nullable=True, comment='升三级奖励'))
    op.add_column('Commision', sa.Column('LevelUpTwo', sa.Integer(), nullable=True, comment='一级升二级要求人数'))
    op.add_column('Commision', sa.Column('LevelUpTwoReward', sa.DECIMAL(scale=2), nullable=True, comment='升二级奖励'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Commision', 'LevelUpTwoReward')
    op.drop_column('Commision', 'LevelUpTwo')
    op.drop_column('Commision', 'LevelUpThreeReward')
    op.drop_column('Commision', 'LevelUpThree')
    op.drop_column('Commision', 'LevelDownZeroRep')
    op.drop_column('Commision', 'LevelDownZero')
    op.drop_column('Commision', 'LevelDownTwoRep')
    op.drop_column('Commision', 'LevelDownTwo')
    op.drop_column('Commision', 'LevelDownOneRep')
    op.drop_column('Commision', 'LevelDownOne')
    op.drop_column('Commision', 'CheckTime')
    # ### end Alembic commands ###
