"""'add_order_share'

Revision ID: 53b5ee1b429c
Revises: 3a8304b03808
Create Date: 2020-07-06 15:16:14.920328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53b5ee1b429c'
down_revision = '3a8304b03808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderMain', sa.Column('UPshareid', sa.String(length=64), nullable=True, comment='分享者id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderMain', 'UPshareid')
    # ### end Alembic commands ###
