"""'order'

Revision ID: 56c9c1ec3dc7
Revises: 2a827944a676
Create Date: 2020-06-12 23:27:16.354414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c9c1ec3dc7'
down_revision = '2a827944a676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Commision',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('Levelcommision', sa.String(length=32), nullable=True),
    sa.Column('InviteNum', sa.Integer(), nullable=True),
    sa.Column('GroupSale', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('PesonalSale', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('InviteNumScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('GroupSaleScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('PesonalSaleScale', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('ReduceRatio', sa.String(length=32), nullable=True),
    sa.Column('IncreaseRatio', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('COid')
    )
    op.create_table('OrderMain',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OMno', sa.String(length=64), nullable=False),
    sa.Column('OPayno', sa.String(length=64), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('OMmount', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('OMtrueMount', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('OMstatus', sa.Integer(), nullable=True),
    sa.Column('OMinRefund', sa.Boolean(), nullable=True),
    sa.Column('OMmessage', sa.String(length=255), nullable=True),
    sa.Column('OMrecvPhone', sa.String(length=11), nullable=False),
    sa.Column('OMrecvName', sa.String(length=11), nullable=False),
    sa.Column('OMrecvAddress', sa.String(length=255), nullable=False),
    sa.Column('PRcreateId', sa.String(length=64), nullable=True),
    sa.Column('OMlogisticType', sa.Integer(), nullable=True),
    sa.Column('OMintegralpayed', sa.Integer(), nullable=True),
    sa.Column('OMpayType', sa.Integer(), nullable=True),
    sa.Column('UPperid', sa.String(length=64), nullable=True),
    sa.Column('UPperid2', sa.String(length=64), nullable=True),
    sa.Column('UPperid3', sa.String(length=64), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRname', sa.String(length=255), nullable=False),
    sa.Column('PRimg', sa.String(length=255), nullable=False),
    sa.Column('OPnum', sa.Integer(), nullable=True),
    sa.Column('OMqrcode', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('OMid')
    )
    op.create_table('OrderPay',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OPayid', sa.String(length=64), nullable=False),
    sa.Column('OPayno', sa.String(length=64), nullable=True),
    sa.Column('OPayType', sa.Integer(), nullable=True),
    sa.Column('OPaytime', sa.DateTime(), nullable=True),
    sa.Column('OPayMount', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('OPaysn', sa.String(length=64), nullable=True),
    sa.Column('OPayJson', sa.Text(), nullable=True),
    sa.Column('OPaymarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('OPayid')
    )
    op.create_index(op.f('ix_OrderPay_OPayno'), 'OrderPay', ['OPayno'], unique=False)
    op.create_table('UserCommission',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UCid', sa.String(length=64), nullable=False),
    sa.Column('UCcommission', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('CommisionFor', sa.Integer(), nullable=True),
    sa.Column('FromUsid', sa.String(length=64), nullable=True),
    sa.Column('UCstatus', sa.Integer(), nullable=True),
    sa.Column('UCtype', sa.Integer(), nullable=True),
    sa.Column('UCendTime', sa.DateTime(), nullable=True),
    sa.Column('PRname', sa.String(length=255), nullable=True),
    sa.Column('PRimg', sa.Text(), nullable=True),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('UCid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserCommission')
    op.drop_index(op.f('ix_OrderPay_OPayno'), table_name='OrderPay')
    op.drop_table('OrderPay')
    op.drop_table('OrderMain')
    op.drop_table('Commision')
    # ### end Alembic commands ###
