"""agreement

Revision ID: 572404f33ff8
Revises: dcd990c26df9
Create Date: 2020-06-13 23:20:33.971168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572404f33ff8'
down_revision = 'dcd990c26df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agreement',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('AMid', sa.String(length=64), nullable=False),
    sa.Column('AMcontent', sa.Text(), nullable=True),
    sa.Column('AMtype', sa.Integer(), nullable=True),
    sa.Column('AMname', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('AMid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Agreement')
    # ### end Alembic commands ###
