"""supplizer_account

Revision ID: 58311a938f3d
Revises: d7152aa42403
Create Date: 2020-06-24 00:18:54.328822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58311a938f3d'
down_revision = 'd7152aa42403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SupplizerAccount',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SAid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('SAbankName', sa.Text(), nullable=True),
    sa.Column('SAbankDetail', sa.Text(), nullable=True),
    sa.Column('SAcardNo', sa.String(length=32), nullable=True),
    sa.Column('SAcardName', sa.Text(), nullable=True),
    sa.Column('SACompanyName', sa.Text(), nullable=True),
    sa.Column('SAICIDcode', sa.Text(), nullable=True),
    sa.Column('SAaddress', sa.Text(), nullable=True),
    sa.Column('SAbankAccount', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SAid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SupplizerAccount')
    # ### end Alembic commands ###
