"""add_sugrade

Revision ID: 655a9ead4150
Revises: 31ee01847844
Create Date: 2020-06-15 18:49:52.835142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '655a9ead4150'
down_revision = '31ee01847844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ActivationType', 'ATTicon')
    op.drop_column('ActivationType', 'ATTtype')
    op.add_column('Supplizer', sa.Column('SUgrade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Supplizer', 'SUgrade')
    op.add_column('ActivationType', sa.Column('ATTtype', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ActivationType', sa.Column('ATTicon', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
