"""product_month_sale_value

Revision ID: 67186446f8d3
Revises: 58311a938f3d
Create Date: 2020-06-24 13:42:29.167324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67186446f8d3'
down_revision = '58311a938f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductMonthSaleValue',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PMSVid', sa.String(length=64), nullable=False),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PMSVnum', sa.BIGINT(), nullable=True),
    sa.Column('PMSVfakenum', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('PMSVid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductMonthSaleValue')
    # ### end Alembic commands ###
