"""'activition'

Revision ID: a64e2baf17e5
Revises: fb09e96670d6
Create Date: 2020-06-13 04:01:50.405558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64e2baf17e5'
down_revision = 'fb09e96670d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ATid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('ATTid', sa.String(length=64), nullable=True),
    sa.Column('ATnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ATid')
    )
    op.create_table('ActivationType',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ATTid', sa.String(length=64), nullable=False),
    sa.Column('ATTname', sa.String(length=256), nullable=True),
    sa.Column('ATTnum', sa.Integer(), nullable=True),
    sa.Column('ATTupperLimit', sa.Integer(), nullable=True),
    sa.Column('ATTdayUpperLimit', sa.Integer(), nullable=True),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ATTid')
    )
    op.create_table('ProductOrderActivation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('POAid', sa.String(length=64), nullable=False),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.Column('ATid', sa.String(length=64), nullable=True),
    sa.Column('POAcontent', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('POAid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductOrderActivation')
    op.drop_table('ActivationType')
    op.drop_table('Activation')
    # ### end Alembic commands ###
