"""product_verifier

Revision ID: bc3585a4303c
Revises: 655a9ead4150
Create Date: 2020-06-16 14:34:47.000398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3585a4303c'
down_revision = '655a9ead4150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductVerifiedRecord',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PVRid', sa.String(length=64), nullable=False),
    sa.Column('ownerId', sa.String(length=64), nullable=True),
    sa.Column('VerifierId', sa.String(length=64), nullable=True),
    sa.Column('OMid', sa.String(length=64), nullable=True),
    sa.Column('param', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('PVRid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductVerifiedRecord')
    # ### end Alembic commands ###
