"""'remove_nullable'

Revision ID: bc8675757153
Revises: a64e2baf17e5
Create Date: 2020-06-13 04:30:07.440206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc8675757153'
down_revision = 'a64e2baf17e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrderMain', 'OMrecvAddress',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('OrderMain', 'OMrecvName',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('OrderMain', 'OMrecvPhone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('OrderMain', 'PRimg',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrderMain', 'PRimg',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('OrderMain', 'OMrecvPhone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('OrderMain', 'OMrecvName',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('OrderMain', 'OMrecvAddress',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
