"""'add'

Revision ID: d7152aa42403
Revises: 24f5346afd15
Create Date: 2020-06-23 17:59:04.445413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7152aa42403'
down_revision = '24f5346afd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Commision', sa.Column('DevideRate', sa.DECIMAL(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Commision', 'DevideRate')
    # ### end Alembic commands ###
