"""index_banner

Revision ID: dcd990c26df9
Revises: bc8675757153
Create Date: 2020-06-13 13:54:18.658823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcd990c26df9'
down_revision = 'bc8675757153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinkContent',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('LCid', sa.String(length=64), nullable=False),
    sa.Column('LCcontent', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('LCid')
    )
    op.create_table('MiniProgramBanner',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('MPBid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True),
    sa.Column('MPBpicture', sa.Text(), nullable=False),
    sa.Column('MPBsort', sa.Integer(), nullable=True),
    sa.Column('MPBshow', sa.Boolean(), nullable=True),
    sa.Column('MPBposition', sa.Integer(), nullable=True),
    sa.Column('contentlink', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('MPBid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MiniProgramBanner')
    op.drop_table('LinkContent')
    # ### end Alembic commands ###
