"""add_product_verifier

Revision ID: fb09e96670d6
Revises: 56c9c1ec3dc7
Create Date: 2020-06-13 00:36:03.766516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb09e96670d6'
down_revision = '56c9c1ec3dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductVerifier',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PVid', sa.String(length=64), nullable=False),
    sa.Column('SUid', sa.String(length=64), nullable=True),
    sa.Column('PVphone', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('PVid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductVerifier')
    # ### end Alembic commands ###
